name: C/C++ CI

on:
  push:
    branches: 
    - "**"
    
env:
  APP_PATH: "BigBrother/src"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: getQT
      run: |
        sudo apt update
        sudo apt update --fix-missing
        sudo apt-get install build-essential
        sudo apt-get install libqwt-qt5-6
        sudo apt-get install qtbase5-dev
    
    - name: Install boost test framework
      run: |
        sudo apt-get install libboost-test-dev
        
    - name: buildSolution
      run: |
        ls
        cd ${{env.APP_PATH}}
        ls
        mkdir ../build 
        cd ../build
        cmake ../src
        make
      
      
      
    
