name: C/C++ CI

on:
  push:
    branches: [ main ]
    
env:
  APP_PATH: "BigBrother/src"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: getQT
      run: |
        sudo apt-get install build-essential
        sudo apt-get install libqwt-qt5-6
        
    - name: buildSolution
      run: |
        ls
        cd ${{env.APP_PATH}}
        ls
        mkdir ../build 
        cd ../build
        cmake ../src
        make
      
      
      
    
